version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.8
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/react-router"
    versions:
    - 5.1.9
