/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LessonLessonIdImport } from './routes/lesson.$lessonId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LessonLessonIdRoute = LessonLessonIdImport.update({
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LessonLessonIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lesson/$lessonId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/lesson/$lessonId": {
      "filePath": "lesson.$lessonId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
